substitutions:
  systemName: bthome-1

esphome:
  name: $systemName

esp32:
  board: esp32dev
  # wemos_d1_mini32

external_components:
  - source:
      type: local
      path: ../../esphome_components/bthome/components

logger:
  level: debug
  # level: info

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80
  ota: false

esp32_ble_tracker:
  scan_parameters:
    active: false

bthome_receiver:
  # dump_unmatched: true
  # dump: unmatched | all
  # dump: unmatched
  dump: all

sensor:
  - platform: bthome_receiver
    mac_address: !secret mac_nappali
    name_prefix: BTHome Nappali
    # dump: unmatched | all
    # dump: all
    sensors:
      - measurement_type: temperature
        name: Temperature
      - measurement_type: humidity
        name: Humidity
      - measurement_type: packet_id
        name: PacketId

  - platform: bthome_receiver
    mac_address: !secret mac_garazs
    name_prefix: BTHome Garazs
    sensors:
      - measurement_type: temperature
        name: Temperature
      - measurement_type: 0x02
        name: Temperature 2
        accuracy_decimals: 2
        unit_of_measurement: °C
      - measurement_type: 0x02
        name: Temperature 3
      - measurement_type: count_large
        name: Count

  - platform: bthome_receiver
    mac_address: !secret mac_dolgozo
    dump: all
    sensors:
      - measurement_type: temperature
        name: BTHome Dolgozó Temperature

binary_sensor:
  - platform: bthome_receiver
    mac_address: !secret mac_garazs
    sensors:
      - measurement_type: opening
        name: BTHome Opening Garazs
